### PR TITLE
Start on allowing compile-time stint. Works for Uint256

### PR DESCRIPTION
**Pull request by mratsim**
This allows compile-time construction of Uint256.

Unfortunately Int256 are much more tricky.

Benefits:
  - Nimbus const will be actually constants https://github.com/status-im/nimbus/blob/master/nimbus/constants.nim. This means that they can be inlined at compile-time and we can make Nimbus more restrictive regarding side-effects.

### CODE REVIEW

**Comment by coffeepots** [comment]
Great work! Compile time Uint256 is a fantastic goal!
Currently there are some tests failing with respect to converting to or from strings though, so will approve when that's sorted.

**Comment by zah** [comment]
I wasn't aware that Nim has issues with working with all of the integer types in the VM. This doesn't sound as something too complicated to fix and it will be probably easier than coming up with clever work-arounds in stint.

**Comment by zah** [comment]
For JS, I guess the best way to support it in Stint is by creating an abstraction that hides the memory storage in either a C array or a JavaScript [ `TypedArray`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray), but I haven't looked at the stint internals very closely yet, so I might be off the mark.

**Comment by mratsim** [comment]
@zah, yes that's what I will do, I will change the backend to an array and lo/hi will be abstraction upon it. That was suggested by @yglukhov a couple months ago.

It's the only way I think to reconcile the need of bitwise ops (need to iterate over an array to be fast, currently done through ptr casting) and math ops (need the recursive lo/hi to be easy to follow) and still allow iteration at compile-time or in JS.

**Pull request merged**
